### ISSUE TITLE
How to add to Epyrus (E-Mail client from "PaleMoon" developer)

### ISSUE THREAD

**Issue by SlySven** [RealityRipple/About-Add-ons#1]
The "Add-ons" page for that EMail client https://addons.epyrus.org/extensions/ derived from Thunderbird in the same manner that Palemoon is derived from Firefox - suggests that this Add-on is compatible with it - but downloading ("Save as file") the file (`{265666C5-D659-5C5A-8C36-9ADA9B367E5B}.xpi`) from `https://realityripple.com/Software/XUL/About-Add-ons/` and trying to install it (via the "Install from file" option on it's add-on page):
![image](https://github.com/user-attachments/assets/b92ee50c-6b88-4fa3-9073-32d95184ed55)

does not yield something that Epyrus can use:
![image](https://github.com/user-attachments/assets/7a95c3ed-e4a0-4107-8646-92e467a80140)

So, what needs to be modified for this addon to get it to work - assuming that it is compatible with this EMail client?

Project homepage: http://www.epyrus.org/ - note the insecure scheme - the certification for the secure connection is messed up as it is not valid for [\*.]eyprus.org, only [\*.]palemoon.org despite them being from the same stable...

**Comment by RealityRipple** [comment]
My extensions ONLY support Pale Moon. Pale Moon is the only listed compatible application, both on the About Add-ons website, and in the readme of this repository.

You can try using the legacy package from this repo, but I can't guarantee any functionality.
